### ISSUE TITLE
Cant Click on Folders

### ISSUE THREAD

**Issue by Kyro3400** [audn/frontend-boilerplate#5]
So i'm on the [website](https://twemoji.netlify.app/#) and for some reason i cant click on the folders?

**Comment by thewilloftheshadow** [comment]
I believe that is because this is still in the prototype stage, its not functional yet

**Comment by Kyro3400** [comment]
> I believe that is because this is still in the prototype stage, its not functional yet

Yes i know that, i'm just saying

**Comment by audn** [comment]
Yea, shutting down project as I didn't know about how easy it is to parse twemoji :P

**Comment by Kyro3400** [comment]
No don’t shut down the project! I’ll help you with it
